name: Build Master

on:
  push:
    branches: [ master, main ]

jobs:
  clippy:
    uses: ./.github/workflows/rust_clippy.yaml
    secrets: inherit

  deps:
    uses: ./.github/workflows/rust_deps.yaml
    secrets: inherit

  fmt:
    uses: ./.github/workflows/rust_fmt.yaml
    secrets: inherit
